### ISSUE TITLE
API Endpoints 

### ISSUE THREAD

**Issue by DavidGOrtega** [kinguinltdhk/Kinguin-eCommerce-API#28]
Hi team!

I have a minor issue with understanding the endpoints. I actually have successfully implemented products and complete life cycle of an order with the endpoint located at:

https://gateway.kinguin.net/esa/api
https://gateway.sandbox.kinguin.net/esa/api

However I found this [swagger Api](https://api.kinguin.net/docs/) but II can't access it using my credentials and I cant also access the same endpoints in my working endpoints. 
Thats maybe an internal API for you?

**Comment by seniorquico** [comment]
I created (by hand) an OpenAPI Specification 3 document for the Kinguin API endpoints that we use (`.txt` extension because GitHub doesn't allow attaching `.json` extensions):

[KinguinApi.oas3.txt](https://github.com/kinguinltdhk/Kinguin-eCommerce-API/files/6290048/KinguinApi.oas3.txt)

No warranties. YMMV. 😉

We use this OpenAPI Specification document to auto-generate our API clients & models.

**Comment by DavidGOrtega** [comment]
@seniorquico thanks! 

It's really interesting that you do the order using the v2 version ```v2/order``` however for me fails having to use v1 and then use v2 for the keys.

I guess then that the docs belongs to an internal Kinguin API and we can not access that. I was thinking to use the helpesk endpoint to automatise the issues with the keys 😞 .

**Comment by DavidGOrtega** [comment]
@seniorquico Do you have an idea what is dispatch used for? I can get the keys without calling dispatch and the order automatically has a dispatch id.
